### ISSUE TITLE
Synlinks: error when extracting archives built with --dereference

### ISSUE THREAD

**Issue by jwaldmann** [haskell/tar#19] opened 2016-05-30 11:33 UTC
When I build an archive with gnu tar, using `--dereference`, it cannot be unpacked by haskell-tar.

Simple test case is here: https://gitlab.imn.htwk-leipzig.de/waldmann/check-tar

This is creating a problem with keter, cf. https://github.com/snoyberg/keter/issues/146

**Comment by jwaldmann** [comment] 2016-05-30 12:20
Ah, keter is not using the bundled `extract` function but rolls its own which silently ignores links: https://github.com/snoyberg/keter/blob/1b10ffabe436e67e51b4a0e4153740d085483239/Codec/Archive/TempTarball.hs#L87 

So, that should be fixed on keter's side, but the bug here still stands. Perhaps it is a documentation bug.

**Comment by dcoutts** [comment] 2016-06-01 13:37
The tar package does not create symlinks (partly because this is not supported on other systems and it's not supported by the directory package). It emulates them in a way that's portable to other platforms like windows by copying the files that are the target of the symlink but this does depend on the order of the files within the archive. If the symlink target is unpacked first then it's ok, but if it's unpacked later then it fails.

What would you suggest? That we emulate it better by maintaining a map of symlinks as we unpack and copy once at the end? Or that we use genuine symlinks on platforms that support it and do what on windows?

Up to know the tar package has mainly been there to support portable archives, rather than arbitrary platform-specific archives.

**Comment by dcoutts** [comment] 2016-09-07 13:17
@jwaldmann ping ^^ if you have any opinion on this, that'd be most welcome.

**Comment by ivanperez-keera** [comment] 2017-05-31 16:58
Symlinks have been supported by `directory` since 1.3.1.0:

https://hackage.haskell.org/package/directory-1.3.1.1/docs/System-Directory.html#v:createFileLink

**Comment by vmchale** [comment] 2020-08-02 19:20
> Up to know the tar package has mainly been there to support portable archives, rather than arbitrary platform-specific archives.

Such things are allowed, no? I mean it's a bit silly perhaps but I think one can e.g. put a file before the directory containing it.

**Comment by Bodigrim** [comment] 2023-11-19 16:35
Probably fixed in #77, at least the reproducer does not fail any more for me.

**Closed as completed by Bodigrim** 2023-11-19 16:35 UTC
